### PR TITLE
Configure dotenv template stuff and Install Mongoose

### PR DESCRIPTION
**Pull request by S1xZ**
Added .env.template file and Configured some environment variables in docker-compose file and also the webserver port variable

===Packages===
+ dotenv
+ Mongoose

### CODE REVIEW

**Comment by Charnkij** [comment]
DB เชื่อมไม่ด้ายยย งานงอก

**Comment by S1xZ** [comment]
Fixed database

===Containers===

[+] Change mongo to version 4.0.2

**Comment by S1xZ** [comment]
แก้แล้วครับพรี่

**Comment by Charnkij** [comment]
[https://discord.com/channels/1009035055647166517/1070570468379197570/1070730089911824474](url)

**Comment by Charnkij** [comment]
elegance-spy-x-family

**Comment by CharnkijCU** [comment]
D ngub

**Review by CharnkijCU — APPROVED** [review]

**Pull request merged**
