### PR TITLE
Feature/auth/reset password

### PR DESCRIPTION
**Pull request by clickCA**
**Description:**

This pull request adds the reset password feature to the authentication module in the app. To test the email sending, use a tool like Mailtrap (https://mailtrap.io/), which allows you to test email sending without actually sending emails to real recipients.
image

**The reset password feature includes the following functionality:**

- A user can request a password reset by providing their email address
- The user will receive an email with a password reset link
- The user can click on the link to reset their password
- The password reset link expires after 1 hour
- The app will validate the password reset token
- The user can update their password using the password reset token

### CODE REVIEW

**Review by S1xZ — CHANGES_REQUESTED** [review]
image

Overall looked great, but there have been a mistake on the email sent maybe?

**Comment by clickCA** [comment]
Ok

**Comment by clickCA** [comment]
Gonna change might be bug on email subject

**Comment by clickCA** [comment]
image

**Comment by clickCA** [comment]
Fixed! as you can see in the picture, the email subject have a username show

**Comment by NatananPh** [comment]
nice one!

**Review by NatananPh — APPROVED** [review]
nice one

**Review by S1xZ — APPROVED** [review]
Les go

**Pull request merged**
