### PR TITLE
Add docker image builder for production

### PR DESCRIPTION
**Pull request by S1xZ**
[x] Added builder scripts for backend image to use in production and frontend development

### CODE REVIEW

**Comment by Nick-solich** [comment]
LGTM!

**Review by clickCA — COMMENTED** [review]
The use of Docker and docker-compose makes it easier to deploy the application in different environments and ensures that the environment is consistent between development and production. The scripts for building, pushing and deploying the Docker images are well organized and make it easier to automate the deployment process.

**Review by clickCA — APPROVED** [review]
it good approve to merge

**Review by Nick-solich — APPROVED** [review]
LGTM

**Pull request merged**
